"""Native Scanner Workbench catalog.

This module intentionally stores Edge-owned scanner templates. The public
TrendSpider store research informs the taxonomy and names, but Edge does not
import TrendSpider code, account-bound scanner definitions, or proprietary
criteria.
"""
from copy import deepcopy


SCANNER_WORKBENCH_SCHEMA_VERSION = "edge.scanner_workbench.v1"
SCANNER_WORKBENCH_SOURCE_POLICY = "edge_native_paraphrased_public_research_not_trendspider_import"

TRENDSPIDER_PUBLIC_SOURCE_URLS = [
    "https://trendspider.com/trading-tools-store/",
    "https://trendspider.com/trading-tools-store/scanners/",
    "https://trendspider.com/trading-tools-store/strategies/",
    "https://trendspider.com/trading-tools-store/indicators/",
    "https://trendspider.com/trading-tools-store/scanners/bullish-engulfing-candle-recent-3-day-scanner/",
    "https://trendspider.com/trading-tools-store/scanners/69c15d-daily-pivot-breakout-scanner/",
    "https://trendspider.com/trading-tools-store/strategies/68371c-supertrend-scalper-long-30-min/",
    "https://trendspider.com/trading-tools-store/collection/investing-legends/",
    "https://trendspider.com/developers/",
]


SCANNERS = [
    {
        "id": "bullish_engulfing_recent_3d",
        "name": "Bullish Engulfing Recent 3-Day",
        "category": "candlestick",
        "description": (
            "Flags symbols that recently printed a bullish engulfing reversal candle so Edge can queue "
            "reversal review before momentum confirmation."
        ),
        "watch_signals": ["bullish_engulfing", "recent_reversal_window", "bullish_close_context"],
        "timeframes": ["1d", "1w"],
        "source_inspiration": "TrendSpider public store: Bullish Engulfing Candle Recent 3-Day Scanner",
        "source_urls": [
            "https://trendspider.com/trading-tools-store/scanners/bullish-engulfing-candle-recent-3-day-scanner/"
        ],
        "requires": ["ohlcv", "candlestick_patterns"],
        "automation_default": "off",
    },
    {
        "id": "ascending_triangle_breakup",
        "name": "Ascending Triangle Breakup",
        "category": "chart_pattern",
        "description": (
            "Looks for a flat resistance shelf with rising higher lows, then marks symbols that push "
            "through the shelf with volume support."
        ),
        "watch_signals": ["horizontal_resistance_break", "higher_low_sequence", "relative_volume"],
        "timeframes": ["15m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Ascending Triangle Breakup Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "swing_points", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "vortex_bullish_extreme",
        "name": "Vortex Bullish Extreme",
        "category": "indicator",
        "description": (
            "Surfaces strong positive Vortex separation where directional pressure is stretched enough "
            "to justify trend-continuation monitoring."
        ),
        "watch_signals": ["vortex_positive_extreme", "directional_separation", "trend_strength"],
        "timeframes": ["30m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Vortex Indicator Bullish Extreme Scanner",
        "source_urls": [
            "https://trendspider.com/trading-tools-store/scanners/vortex-indicator-bullish-extreme-scanner/"
        ],
        "requires": ["ohlcv", "vortex_indicator"],
        "automation_default": "off",
    },
    {
        "id": "donchian_channel_price_action",
        "name": "Donchian Channel Price Action",
        "category": "breakout",
        "description": (
            "Tracks symbols pressing against recent Donchian channel extremes so Edge can separate "
            "fresh breakout attempts from range noise."
        ),
        "watch_signals": ["donchian_high_test", "donchian_low_test", "range_expansion"],
        "timeframes": ["1h", "1d"],
        "source_inspiration": "TrendSpider public store: Donchian Channel Price Action scanner family",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "donchian_channel"],
        "automation_default": "off",
    },
    {
        "id": "upper_bollinger_band_pierce",
        "name": "Upper Bollinger Band Pierce",
        "category": "volatility",
        "description": (
            "Marks closes or intrabar pushes beyond the upper Bollinger Band when volatility expansion "
            "may be starting."
        ),
        "watch_signals": ["upper_band_pierce", "bandwidth_expansion", "close_location"],
        "timeframes": ["15m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Bollinger Band scanner family",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "bollinger_bands"],
        "automation_default": "off",
    },
    {
        "id": "small_cap_radar",
        "name": "Small Cap Radar",
        "category": "universe",
        "description": (
            "Filters lower-market-cap names for liquidity, price movement, and volume expansion before "
            "they enter any high-risk watch flow."
        ),
        "watch_signals": ["small_cap_universe", "liquidity_floor", "volume_expansion"],
        "timeframes": ["5m", "15m", "1d"],
        "source_inspiration": "TrendSpider public store: small-cap scanner concepts",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "market_cap", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "death_cross_spotter",
        "name": "Death Cross Spotter",
        "category": "moving_average",
        "description": "Watches for major bearish moving-average crosses and keeps them out of long-only momentum lists.",
        "watch_signals": ["sma_50_below_sma_200", "bearish_trend_transition", "trend_filter"],
        "timeframes": ["1d"],
        "source_inspiration": "TrendSpider public store: moving-average crossover scanner concepts",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "sma_50", "sma_200"],
        "automation_default": "off",
    },
    {
        "id": "bb_kc_squeeze_anchored_vwap",
        "name": "BB/KC Squeeze + Anchored VWAP",
        "category": "volatility",
        "description": (
            "Finds Bollinger/Keltner compression while requiring price context around anchored VWAP so "
            "Edge watches only squeezes with a useful reference level."
        ),
        "watch_signals": ["bb_kc_squeeze", "anchored_vwap_context", "compression_release"],
        "timeframes": ["15m", "30m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: squeeze and anchored VWAP scanner concepts",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "bollinger_bands", "keltner_channels", "anchored_vwap"],
        "automation_default": "off",
    },
    {
        "id": "ichimoku_tenkan_kijun_cross",
        "name": "Ichimoku Tenkan/Kijun Cross",
        "category": "indicator",
        "description": (
            "Monitors Tenkan and Kijun crosses with cloud position context to distinguish trend "
            "confirmation from weak countertrend crosses."
        ),
        "watch_signals": ["tenkan_kijun_cross", "cloud_position", "trend_confirmation"],
        "timeframes": ["1h", "1d"],
        "source_inspiration": "TrendSpider public store: Ichimoku crossover scanner concepts",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "ichimoku"],
        "automation_default": "off",
    },
    {
        "id": "orb_15m_high_breakout",
        "name": "15-Min ORB High Breakout",
        "category": "orb",
        "description": (
            "Watches for symbols clearing the first 15-minute opening range high with enough volume and "
            "spread quality for review."
        ),
        "watch_signals": ["orb_15m_high_break", "opening_volume", "spread_quality"],
        "timeframes": ["1m", "5m", "15m"],
        "source_inspiration": "TrendSpider public store: 15min ORB High Breakout Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/15min-orb-high-breakout-scanner/"],
        "requires": ["ohlcv", "orb_levels", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "orb_volume_gap_breakout",
        "name": "ORB Volume Gap Breakout",
        "category": "orb",
        "description": (
            "Combines gap direction, opening range breakout, and relative volume so Edge can prioritize "
            "opening-drive candidates."
        ),
        "watch_signals": ["gap_direction", "orb_breakout", "relative_volume"],
        "timeframes": ["1m", "5m", "15m", "30m"],
        "source_inspiration": "Edge native ORB roadmap plus TrendSpider ORB scanner taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "orb_levels", "gap_percent", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "premarket_orb_range_expansion",
        "name": "Premarket ORB Range Expansion",
        "category": "orb",
        "description": (
            "Uses premarket range width, current price location, and volume ramp to decide which symbols "
            "deserve attention before the regular open."
        ),
        "watch_signals": ["premarket_30m_range", "premarket_volume", "range_expansion"],
        "timeframes": ["1m", "5m", "30m"],
        "source_inspiration": "Edge native ORB roadmap plus public ORB scanner patterns",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/"],
        "requires": ["ohlcv", "premarket_session", "orb_levels"],
        "automation_default": "off",
    },
    {
        "id": "market_open_orb_continuation",
        "name": "Market Open ORB Continuation",
        "category": "orb",
        "description": (
            "Keeps a symbol on watch after the initial ORB break only when pullbacks hold range edge, "
            "VWAP, or the midpoint."
        ),
        "watch_signals": ["orb_retest_hold", "vwap_hold", "midpoint_hold"],
        "timeframes": ["5m", "15m", "30m"],
        "source_inspiration": "Edge native ORB roadmap",
        "source_urls": ["https://trendspider.com/developers/"],
        "requires": ["ohlcv", "orb_levels", "vwap"],
        "automation_default": "off",
    },
    {
        "id": "daily_pivot_breakout",
        "name": "Daily Pivot Breakout",
        "category": "breakout",
        "description": (
            "Finds confirmed daily pivot-high breaks after the close and marks them for next-session "
            "follow-through research."
        ),
        "watch_signals": ["daily_pivot_high_break", "momentum_filter", "volume_filter"],
        "timeframes": ["1d"],
        "source_inspiration": "TrendSpider public store: Daily Pivot Breakout Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/69c15d-daily-pivot-breakout-scanner/"],
        "requires": ["ohlcv", "pivot_highs", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "daily_gainers_10_pct",
        "name": "10%+ Daily Gainers",
        "category": "momentum",
        "description": "Marks stocks or ETFs up at least 10 percent on the day for momentum or exhaustion review.",
        "watch_signals": ["daily_change_pct_gt_10", "momentum_extension", "volume_check"],
        "timeframes": ["1d", "15m"],
        "source_inspiration": "TrendSpider public store: 10%+ Daily Gainers Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/10-daily-gainers-scanner/"],
        "requires": ["ohlcv", "daily_change_pct"],
        "automation_default": "off",
    },
    {
        "id": "rsi_divergence",
        "name": "RSI Divergence",
        "category": "momentum",
        "description": (
            "Compares price swings against RSI swings to identify potential weakening trends before "
            "price confirms the turn."
        ),
        "watch_signals": ["bullish_rsi_divergence", "bearish_rsi_divergence", "swing_confirmation"],
        "timeframes": ["30m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: RSI Divergence Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/rsi-divergence-scanner/"],
        "requires": ["ohlcv", "rsi_14", "swing_points"],
        "automation_default": "off",
    },
    {
        "id": "rising_wedge_breakout",
        "name": "Rising Wedge Breakout",
        "category": "chart_pattern",
        "description": "Tracks wedge compression and breakout direction so Edge can flag late-stage trend resolution.",
        "watch_signals": ["rising_wedge", "wedge_break", "volume_confirmation"],
        "timeframes": ["1h", "1d"],
        "source_inspiration": "TrendSpider public store: Rising Wedge Breakout Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/rising-wedge-breakout-scanner/"],
        "requires": ["ohlcv", "swing_points", "pattern_engine"],
        "automation_default": "off",
    },
    {
        "id": "descending_channel_in_force",
        "name": "Descending Channel In-Force",
        "category": "chart_pattern",
        "description": "Identifies orderly downward channels that are still respecting both trend boundaries.",
        "watch_signals": ["descending_channel", "channel_respect", "trend_boundary"],
        "timeframes": ["1h", "1d"],
        "source_inspiration": "TrendSpider public store: Descending Channel In-Force Scanner",
        "source_urls": ["https://trendspider.com/trading-tools-store/scanners/descending-channel-in-force-scanner/"],
        "requires": ["ohlcv", "swing_points", "pattern_engine"],
        "automation_default": "off",
    },
    {
        "id": "high_volume_price_gappers",
        "name": "High Volume Price Gappers",
        "category": "gap",
        "description": "Ranks gap names by volume participation so the open watchlist emphasizes liquid moves.",
        "watch_signals": ["gap_percent", "relative_volume", "premarket_liquidity"],
        "timeframes": ["1m", "5m", "1d"],
        "source_inspiration": "TrendSpider public store: Free Trading Ideas taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/"],
        "requires": ["ohlcv", "gap_percent", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "stocks_breaking_out_chart_patterns",
        "name": "Stocks Breaking Out of Chart Patterns",
        "category": "chart_pattern",
        "description": "Collects pattern breaks across triangles, flags, wedges, and channels into one review queue.",
        "watch_signals": ["pattern_breakout", "breakout_volume", "pattern_quality"],
        "timeframes": ["15m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Free Trading Ideas taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/"],
        "requires": ["ohlcv", "pattern_engine", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "current_bullish_momentum",
        "name": "Current Bullish Momentum",
        "category": "momentum",
        "description": "Highlights symbols with aligned trend, positive momentum, and current session participation.",
        "watch_signals": ["trend_alignment", "momentum_positive", "volume_participation"],
        "timeframes": ["15m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Free Trading Ideas taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/"],
        "requires": ["ohlcv", "ema_stack", "rsi_14", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "fundamental_value_technical_reversal",
        "name": "Fundamental Value + Technical Reversals",
        "category": "hybrid",
        "description": "Pairs value-oriented fundamentals with early technical reversal signals for research-only review.",
        "watch_signals": ["value_screen", "reversal_candle", "support_reclaim"],
        "timeframes": ["1d", "1w"],
        "source_inspiration": "TrendSpider public store: Free Trading Ideas taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/"],
        "requires": ["fundamentals", "ohlcv", "candlestick_patterns"],
        "automation_default": "off",
    },
    {
        "id": "consistent_fundamental_growth",
        "name": "Consistent Fundamental Growth Stories",
        "category": "hybrid",
        "description": "Surfaces symbols with repeatable growth characteristics that also maintain constructive trend posture.",
        "watch_signals": ["growth_screen", "trend_health", "relative_strength"],
        "timeframes": ["1d", "1w"],
        "source_inspiration": "TrendSpider public store: Free Trading Ideas taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/"],
        "requires": ["fundamentals", "ohlcv", "relative_strength"],
        "automation_default": "off",
    },
    {
        "id": "upcoming_growth_company_earnings",
        "name": "Upcoming Growth Company Earnings",
        "category": "event",
        "description": "Builds an earnings watch queue for growth names so Edge can monitor pre-event volatility and gaps.",
        "watch_signals": ["earnings_calendar", "growth_screen", "pre_event_volatility"],
        "timeframes": ["1d"],
        "source_inspiration": "TrendSpider public store: Free Trading Ideas taxonomy",
        "source_urls": ["https://trendspider.com/trading-tools-store/"],
        "requires": ["fundamentals", "earnings_calendar", "ohlcv"],
        "automation_default": "off",
    },
    {
        "id": "sector_rotation_matrix",
        "name": "Sector Rotation Matrix",
        "category": "relative_strength",
        "description": "Compares sector momentum against a benchmark to highlight rotation into or out of risk groups.",
        "watch_signals": ["sector_relative_strength", "sector_momentum", "benchmark_comparison"],
        "timeframes": ["1d", "1w"],
        "source_inspiration": "TrendSpider public store: Sector Rotation Matrix indicator",
        "source_urls": ["https://trendspider.com/trading-tools-store/indicators/696077-sector-rotation-matrix/"],
        "requires": ["ohlcv", "sector_universe", "relative_strength"],
        "automation_default": "off",
    },
    {
        "id": "moving_average_trend_identifier",
        "name": "Moving Average Trend Identifier",
        "category": "moving_average",
        "description": "Classifies candles by their relationship to major moving averages for fast trend-state filtering.",
        "watch_signals": ["ma_stack_state", "candle_position_vs_ma", "trend_state"],
        "timeframes": ["1h", "1d"],
        "source_inspiration": "TrendSpider public store: Moving Average Trend Identifier",
        "source_urls": ["https://trendspider.com/trading-tools-store/indicators/moving-average-trend-identifier/"],
        "requires": ["ohlcv", "sma_10", "sma_20", "sma_50", "sma_100", "sma_200"],
        "automation_default": "off",
    },
    {
        "id": "multi_timeframe_high_low_levels",
        "name": "Multi-Timeframe High/Low Levels",
        "category": "levels",
        "description": "Tracks daily, weekly, monthly, yearly, and 52-week ranges as decision context for breakouts.",
        "watch_signals": ["period_high_distance", "period_low_distance", "range_context"],
        "timeframes": ["1d", "1w"],
        "source_inspiration": "TrendSpider public store: Multi-Timeframe High/Low Levels",
        "source_urls": ["https://trendspider.com/trading-tools-store/indicators/multi-timeframe-high-low-levels/"],
        "requires": ["ohlcv", "rolling_highs_lows"],
        "automation_default": "off",
    },
    {
        "id": "swing_detector_reversal",
        "name": "Swing Detector Reversal",
        "category": "price_action",
        "description": "Finds three-candle failed-break structures that may precede a reversal from a swing extreme.",
        "watch_signals": ["failed_breakdown", "failed_breakout", "three_candle_reversal"],
        "timeframes": ["15m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Swing Detector",
        "source_urls": ["https://trendspider.com/trading-tools-store/indicators/6877e1-swing-detector/"],
        "requires": ["ohlcv", "swing_points", "candlestick_patterns"],
        "automation_default": "off",
    },
    {
        "id": "support_resistance_strength",
        "name": "Support/Resistance Strength",
        "category": "levels",
        "description": "Scores repeated level reactions so Edge can favor cleaner breakouts and reject crowded chop.",
        "watch_signals": ["level_touch_count", "reaction_strength", "break_or_reject"],
        "timeframes": ["15m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: Support/Resistance Strength",
        "source_urls": ["https://trendspider.com/trading-tools-store/indicators/696fe0-support-resistance-strength/"],
        "requires": ["ohlcv", "swing_points", "level_scoring"],
        "automation_default": "off",
    },
    {
        "id": "pe_ratio_comparison",
        "name": "P/E Ratio Comparison",
        "category": "fundamental",
        "description": "Compares valuation across a configured peer basket and tags outliers for research-only review.",
        "watch_signals": ["pe_ratio", "peer_comparison", "valuation_outlier"],
        "timeframes": ["1d", "1w"],
        "source_inspiration": "TrendSpider public store: P/E Ratio Comparison Indicator",
        "source_urls": ["https://trendspider.com/trading-tools-store/indicators/pe-ratio-indicator/"],
        "requires": ["fundamentals", "peer_basket"],
        "automation_default": "off",
    },
    {
        "id": "sector_industry_market_metrics",
        "name": "Sector, Industry, Market Cap & Change Metrics",
        "category": "context",
        "description": "Adds sector, industry, size, and period-change metadata to scanner candidates before ranking.",
        "watch_signals": ["sector", "industry", "market_cap", "period_change"],
        "timeframes": ["1d"],
        "source_inspiration": "TrendSpider public store: Sector, Industry, Market Cap & Change Metrics",
        "source_urls": [
            "https://trendspider.com/trading-tools-store/indicators/sector-industry-market-cap-change-metrics/"
        ],
        "requires": ["fundamentals", "ohlcv"],
        "automation_default": "off",
    },
    {
        "id": "vwap_reclaim",
        "name": "VWAP Reclaim",
        "category": "intraday",
        "description": "Flags symbols that regain VWAP after a weak open while volume and spread remain tradable.",
        "watch_signals": ["vwap_reclaim", "intraday_higher_low", "volume_confirmation"],
        "timeframes": ["1m", "5m", "15m"],
        "source_inspiration": "Edge native intraday scanner concept",
        "source_urls": ["https://trendspider.com/developers/"],
        "requires": ["ohlcv", "vwap", "relative_volume"],
        "automation_default": "off",
    },
    {
        "id": "macd_bull_cross",
        "name": "MACD Bull Cross",
        "category": "momentum",
        "description": "Watches MACD line crosses above signal with histogram expansion and trend-context filters.",
        "watch_signals": ["macd_line_cross_signal", "histogram_expansion", "trend_filter"],
        "timeframes": ["30m", "1h", "1d"],
        "source_inspiration": "TrendSpider public store: MACD Crossover strategy family",
        "source_urls": ["https://trendspider.com/trading-tools-store/strategies/"],
        "requires": ["ohlcv", "macd"],
        "automation_default": "off",
    },
]


RECOMMENDED_TICKERS = [
    {
        "symbol": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "asset_class": "ETF",
        "liquidity_profile": "core_index",
        "recommended_for": ["current_bullish_momentum", "macd_bull_cross", "bb_kc_squeeze_anchored_vwap"],
        "notes": "Core benchmark and crossover test symbol referenced by public strategy examples.",
    },
    {
        "symbol": "QQQ",
        "name": "Invesco QQQ Trust",
        "asset_class": "ETF",
        "liquidity_profile": "core_index",
        "recommended_for": ["orb_volume_gap_breakout", "market_open_orb_continuation", "sector_rotation_matrix"],
        "notes": "High-liquidity technology benchmark used by public SuperTrend and reversal strategy examples.",
    },
    {
        "symbol": "IWM",
        "name": "iShares Russell 2000 ETF",
        "asset_class": "ETF",
        "liquidity_profile": "small_cap_index",
        "recommended_for": ["small_cap_radar", "daily_gainers_10_pct"],
        "notes": "Useful baseline for lower-cap risk appetite and small-cap breadth.",
    },
    {
        "symbol": "DIA",
        "name": "SPDR Dow Jones Industrial Average ETF",
        "asset_class": "ETF",
        "liquidity_profile": "core_index",
        "recommended_for": ["moving_average_trend_identifier", "sector_rotation_matrix"],
        "notes": "Large-cap industrial benchmark for rotation context.",
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_large_cap",
        "recommended_for": ["upper_bollinger_band_pierce", "bb_kc_squeeze_anchored_vwap"],
        "notes": "Mentioned in public Bollinger Band Breakout strategy examples.",
    },
    {
        "symbol": "SHOP",
        "name": "Shopify",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_growth",
        "recommended_for": ["macd_bull_cross", "current_bullish_momentum"],
        "notes": "Mentioned in public MACD crossover strategy examples.",
    },
    {
        "symbol": "OXY",
        "name": "Occidental Petroleum",
        "asset_class": "Equity",
        "liquidity_profile": "energy_large_cap",
        "recommended_for": ["bullish_engulfing_recent_3d", "fundamental_value_technical_reversal"],
        "notes": "Mentioned in public hammer reversal strategy examples.",
    },
    {
        "symbol": "AAPL",
        "name": "Apple",
        "asset_class": "Equity",
        "liquidity_profile": "mega_cap",
        "recommended_for": ["moving_average_trend_identifier", "pe_ratio_comparison"],
        "notes": "Peer-comparison and trend-baseline name referenced by public indicator examples.",
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft",
        "asset_class": "Equity",
        "liquidity_profile": "mega_cap",
        "recommended_for": ["pe_ratio_comparison", "consistent_fundamental_growth"],
        "notes": "Mega-cap peer name referenced by public P/E comparison examples.",
    },
    {
        "symbol": "GOOGL",
        "name": "Alphabet",
        "asset_class": "Equity",
        "liquidity_profile": "mega_cap",
        "recommended_for": ["pe_ratio_comparison", "consistent_fundamental_growth"],
        "notes": "Mega-cap peer name referenced by public P/E comparison examples.",
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_mega_cap",
        "recommended_for": ["orb_volume_gap_breakout", "daily_gainers_10_pct", "bb_kc_squeeze_anchored_vwap"],
        "notes": "High-volume momentum candidate and peer-comparison name referenced by public indicator examples.",
    },
    {
        "symbol": "TSLA",
        "name": "Tesla",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_large_cap",
        "recommended_for": ["macd_bull_cross", "orb_volume_gap_breakout", "daily_gainers_10_pct"],
        "notes": "Mentioned by public MACD and EMA crossover strategy examples.",
    },
    {
        "symbol": "AVGO",
        "name": "Broadcom",
        "asset_class": "Equity",
        "liquidity_profile": "large_cap_semiconductor",
        "recommended_for": ["donchian_channel_price_action", "multi_timeframe_high_low_levels"],
        "notes": "Mentioned in public Turtle Traders strategy examples.",
    },
    {
        "symbol": "ES1!",
        "name": "S&P 500 Continuous Futures",
        "asset_class": "Futures",
        "liquidity_profile": "index_future",
        "recommended_for": ["donchian_channel_price_action", "market_open_orb_continuation"],
        "notes": "TrendSpider-format futures symbol mentioned by public Turtle strategy examples; provider support may vary.",
    },
    {
        "symbol": "META",
        "name": "Meta Platforms",
        "asset_class": "Equity",
        "liquidity_profile": "mega_cap",
        "recommended_for": ["high_volume_price_gappers", "current_bullish_momentum"],
        "notes": "Included from Edge's existing operations universe.",
    },
    {
        "symbol": "AMZN",
        "name": "Amazon",
        "asset_class": "Equity",
        "liquidity_profile": "mega_cap",
        "recommended_for": ["upcoming_growth_company_earnings", "consistent_fundamental_growth"],
        "notes": "Large liquid growth name for earnings and momentum scans.",
    },
    {
        "symbol": "COIN",
        "name": "Coinbase",
        "asset_class": "Equity",
        "liquidity_profile": "crypto_proxy",
        "recommended_for": ["daily_gainers_10_pct", "orb_volume_gap_breakout"],
        "notes": "High-beta crypto proxy for momentum and gap monitoring.",
    },
    {
        "symbol": "HOOD",
        "name": "Robinhood Markets",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_fintech",
        "recommended_for": ["daily_gainers_10_pct", "small_cap_radar"],
        "notes": "Liquid fintech proxy for volatility expansion scans.",
    },
    {
        "symbol": "XOM",
        "name": "Exxon Mobil",
        "asset_class": "Equity",
        "liquidity_profile": "energy_large_cap",
        "recommended_for": ["sector_rotation_matrix", "moving_average_trend_identifier"],
        "notes": "Energy rotation watch candidate.",
    },
    {
        "symbol": "CVX",
        "name": "Chevron",
        "asset_class": "Equity",
        "liquidity_profile": "energy_large_cap",
        "recommended_for": ["sector_rotation_matrix", "moving_average_trend_identifier"],
        "notes": "Energy peer for sector rotation comparison.",
    },
    {
        "symbol": "JPM",
        "name": "JPMorgan Chase",
        "asset_class": "Equity",
        "liquidity_profile": "financial_large_cap",
        "recommended_for": ["sector_rotation_matrix", "multi_timeframe_high_low_levels"],
        "notes": "Financial sector anchor for rotation checks.",
    },
    {
        "symbol": "SMCI",
        "name": "Super Micro Computer",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_growth",
        "recommended_for": ["daily_gainers_10_pct", "bb_kc_squeeze_anchored_vwap"],
        "notes": "High-beta semiconductor infrastructure watch candidate.",
    },
    {
        "symbol": "PLTR",
        "name": "Palantir",
        "asset_class": "Equity",
        "liquidity_profile": "high_beta_growth",
        "recommended_for": ["current_bullish_momentum", "upper_bollinger_band_pierce"],
        "notes": "Liquid momentum name for trend and extension scans.",
    },
]


STRATEGIES = [
    {
        "id": "orb_momentum_continuation",
        "name": "ORB Momentum Continuation",
        "description": "Entertain long watch intent only after ORB high break, VWAP support, and volume confirmation align.",
        "scanner_ids": ["orb_15m_high_breakout", "orb_volume_gap_breakout", "market_open_orb_continuation"],
        "indicator_ids": ["opening_range", "vwap", "relative_volume", "atr"],
        "risk_notes": "Selection-only in this slice; later automation should require spread and buying-power checks.",
        "default_mode": "paper_watch",
    },
    {
        "id": "squeeze_breakout_confirmation",
        "name": "Squeeze Breakout Confirmation",
        "description": "Combine BB/KC compression release, anchored VWAP position, and volume expansion before ranking.",
        "scanner_ids": ["bb_kc_squeeze_anchored_vwap", "upper_bollinger_band_pierce"],
        "indicator_ids": ["bollinger_bands", "keltner_channels", "anchored_vwap", "relative_volume"],
        "risk_notes": "Avoid automatic entries during low-liquidity compression breaks.",
        "default_mode": "paper_watch",
    },
    {
        "id": "supertrend_scalper_long",
        "name": "SuperTrend Scalper Long",
        "description": "Track liquid intraday names above SuperTrend context and long-period SMA with RSI above neutral.",
        "scanner_ids": ["current_bullish_momentum", "moving_average_trend_identifier"],
        "indicator_ids": ["supertrend", "sma_90", "rsi_14"],
        "risk_notes": "Use profit target, stop, and time-based invalidation before any live handoff.",
        "default_mode": "paper_watch",
    },
    {
        "id": "turtle_breakout_long",
        "name": "Turtle Breakout Long",
        "description": "Watch Donchian and multi-timeframe range breaks with ATR context for trend-following candidates.",
        "scanner_ids": ["donchian_channel_price_action", "multi_timeframe_high_low_levels"],
        "indicator_ids": ["donchian_channels", "atr", "period_high_low"],
        "risk_notes": "ATR risk sizing is required before execution use.",
        "default_mode": "paper_watch",
    },
    {
        "id": "macd_crossover_long",
        "name": "MACD Crossover Long",
        "description": "Rank bullish MACD crosses only when trend filter and liquidity checks support follow-through.",
        "scanner_ids": ["macd_bull_cross", "current_bullish_momentum"],
        "indicator_ids": ["macd", "ema_stack", "relative_volume"],
        "risk_notes": "Reject crosses against major moving-average trend unless explicitly overridden.",
        "default_mode": "paper_watch",
    },
    {
        "id": "candlestick_reversal_confirmation",
        "name": "Candlestick Reversal Confirmation",
        "description": "Use engulfing or swing-reversal patterns as alerts, then require level reclaim and momentum check.",
        "scanner_ids": ["bullish_engulfing_recent_3d", "swing_detector_reversal", "support_resistance_strength"],
        "indicator_ids": ["candlestick_pattern_state", "support_resistance_strength", "rsi_14"],
        "risk_notes": "Candlestick signals are research triggers, not standalone entry instructions.",
        "default_mode": "paper_watch",
    },
    {
        "id": "gap_and_hold",
        "name": "Gap-and-Hold",
        "description": "Prioritize high-volume gappers that hold VWAP, opening range midpoint, or premarket high.",
        "scanner_ids": ["high_volume_price_gappers", "orb_volume_gap_breakout", "vwap_reclaim"],
        "indicator_ids": ["gap_percent", "vwap", "opening_range", "relative_volume"],
        "risk_notes": "Do not arm after large spread widening or failed VWAP reclaim.",
        "default_mode": "paper_watch",
    },
    {
        "id": "gap_fade_reversal",
        "name": "Gap Fade Reversal",
        "description": "Watch gap extensions that fail to hold range edge and produce reversal candle confirmation.",
        "scanner_ids": ["high_volume_price_gappers", "swing_detector_reversal", "support_resistance_strength"],
        "indicator_ids": ["gap_percent", "vwap", "candlestick_pattern_state", "atr"],
        "risk_notes": "Fade setups require strict invalidation at session high or low.",
        "default_mode": "paper_watch",
    },
    {
        "id": "sector_rotation_relative_momentum",
        "name": "Sector Rotation Relative Momentum",
        "description": "Rank sector and industry candidates by relative strength, momentum, and benchmark position.",
        "scanner_ids": ["sector_rotation_matrix", "sector_industry_market_metrics"],
        "indicator_ids": ["relative_strength", "sector_rotation_matrix", "period_change"],
        "risk_notes": "Rotation signals are portfolio context until tied to position sizing rules.",
        "default_mode": "paper_watch",
    },
    {
        "id": "daily_pivot_follow_through",
        "name": "Daily Pivot Follow-Through",
        "description": "Build next-day watch intent from confirmed daily pivot breakouts and trailing-stop context.",
        "scanner_ids": ["daily_pivot_breakout", "multi_timeframe_high_low_levels"],
        "indicator_ids": ["pivot_high_low", "atr", "relative_volume"],
        "risk_notes": "Designed for next-session review, not intraday instant entries.",
        "default_mode": "paper_watch",
    },
    {
        "id": "legends_inspired_technical_growth",
        "name": "Legends-Inspired Technical Growth Pack",
        "description": "Distills CANSLIM, Stage Analysis, VCP, Darvas, Turtle, value, quality, and GARP ideas into Edge watch packs.",
        "scanner_ids": [
            "consistent_fundamental_growth",
            "fundamental_value_technical_reversal",
            "donchian_channel_price_action",
            "support_resistance_strength",
        ],
        "indicator_ids": ["relative_strength", "period_high_low", "support_resistance_strength", "pe_ratio"],
        "risk_notes": "Research pack only; public investor frameworks are not endorsements or guarantees.",
        "default_mode": "paper_watch",
    },
]


INDICATORS = [
    {
        "id": "opening_range",
        "name": "Opening Range",
        "description": "Tracks session high, low, midpoint, width, and breakout side for ORB workflows.",
        "parameters": ["session", "minutes", "breakout_side"],
        "used_by": ["orb_momentum_continuation", "gap_and_hold"],
    },
    {
        "id": "anchored_vwap",
        "name": "Anchored VWAP",
        "description": "Provides event-anchored average price context for squeeze and breakout candidates.",
        "parameters": ["anchor_time", "price_source"],
        "used_by": ["squeeze_breakout_confirmation"],
    },
    {
        "id": "vwap",
        "name": "VWAP",
        "description": "Intraday volume-weighted average price used for reclaim, hold, and rejection context.",
        "parameters": ["session", "price_source"],
        "used_by": ["orb_momentum_continuation", "gap_and_hold", "gap_fade_reversal"],
    },
    {
        "id": "bollinger_bands",
        "name": "Bollinger Bands",
        "description": "Measures volatility envelopes and upper/lower band pierces.",
        "parameters": ["length", "standard_deviations"],
        "used_by": ["squeeze_breakout_confirmation"],
    },
    {
        "id": "keltner_channels",
        "name": "Keltner Channels",
        "description": "ATR-based channel used with Bollinger Bands to identify compression.",
        "parameters": ["length", "atr_length", "multiplier"],
        "used_by": ["squeeze_breakout_confirmation"],
    },
    {
        "id": "donchian_channels",
        "name": "Donchian Channels",
        "description": "Rolling high/low breakout channel used for Turtle-style trend following.",
        "parameters": ["lookback"],
        "used_by": ["turtle_breakout_long"],
    },
    {
        "id": "macd",
        "name": "MACD",
        "description": "Momentum crossover and histogram expansion model.",
        "parameters": ["fast", "slow", "signal"],
        "used_by": ["macd_crossover_long"],
    },
    {
        "id": "rsi_14",
        "name": "RSI 14",
        "description": "Momentum oscillator used for neutral-line confirmation, divergence, and reversal checks.",
        "parameters": ["length"],
        "used_by": ["supertrend_scalper_long", "candlestick_reversal_confirmation"],
    },
    {
        "id": "vortex_indicator",
        "name": "Vortex Indicator",
        "description": "Directional movement indicator used to classify bullish or bearish extremes.",
        "parameters": ["length", "extreme_threshold"],
        "used_by": ["vortex_bullish_extreme"],
    },
    {
        "id": "ichimoku",
        "name": "Ichimoku Tenkan/Kijun",
        "description": "Trend, cross, and cloud-position context for Ichimoku-based watch signals.",
        "parameters": ["tenkan", "kijun", "senkou_b"],
        "used_by": ["ichimoku_tenkan_kijun_cross"],
    },
    {
        "id": "relative_volume",
        "name": "Relative Volume",
        "description": "Compares current volume against recent baseline participation.",
        "parameters": ["baseline_bars", "minimum_ratio"],
        "used_by": ["orb_momentum_continuation", "squeeze_breakout_confirmation", "gap_and_hold"],
    },
    {
        "id": "ema_stack",
        "name": "EMA Stack",
        "description": "Fast-to-slow EMA ordering and slope filter for trend alignment.",
        "parameters": ["fast", "medium", "slow"],
        "used_by": ["macd_crossover_long", "current_bullish_momentum"],
    },
    {
        "id": "sma_90",
        "name": "SMA 90",
        "description": "Long intraday trend filter used by SuperTrend-style scalping logic.",
        "parameters": ["length"],
        "used_by": ["supertrend_scalper_long"],
    },
    {
        "id": "supertrend",
        "name": "SuperTrend",
        "description": "ATR-based trend-following state and trailing level.",
        "parameters": ["atr_length", "multiplier"],
        "used_by": ["supertrend_scalper_long"],
    },
    {
        "id": "atr",
        "name": "ATR",
        "description": "Average true range used for stop distance, volatility gating, and position sizing context.",
        "parameters": ["length"],
        "used_by": ["turtle_breakout_long", "daily_pivot_follow_through", "gap_fade_reversal"],
    },
    {
        "id": "support_resistance_strength",
        "name": "Support/Resistance Strength",
        "description": "Scores level quality by touches, reactions, recency, and break behavior.",
        "parameters": ["lookback", "touch_tolerance", "decay"],
        "used_by": ["candlestick_reversal_confirmation", "legends_inspired_technical_growth"],
    },
    {
        "id": "relative_strength",
        "name": "Relative Strength",
        "description": "Benchmarks symbol or sector performance against SPY or another configured benchmark.",
        "parameters": ["benchmark", "lookback"],
        "used_by": ["sector_rotation_relative_momentum", "legends_inspired_technical_growth"],
    },
    {
        "id": "period_high_low",
        "name": "Multi-Period High/Low",
        "description": "Daily, weekly, monthly, yearly, and 52-week high/low distance calculations.",
        "parameters": ["periods", "distance_units"],
        "used_by": ["daily_pivot_follow_through", "legends_inspired_technical_growth"],
    },
    {
        "id": "gap_percent",
        "name": "Gap Percent",
        "description": "Measures current session open or premarket price displacement against the prior close.",
        "parameters": ["reference_close", "session"],
        "used_by": ["gap_and_hold", "gap_fade_reversal"],
    },
    {
        "id": "period_change",
        "name": "Period Change Metrics",
        "description": "DTD, WTD, MTD, and YTD return context for rotation and performance ranking.",
        "parameters": ["periods", "benchmark"],
        "used_by": ["sector_rotation_relative_momentum"],
    },
    {
        "id": "pivot_high_low",
        "name": "Pivot High/Low",
        "description": "Confirms recent swing pivot highs and lows for breakout and trailing-stop context.",
        "parameters": ["left_bars", "right_bars", "confirmation_bars"],
        "used_by": ["daily_pivot_follow_through"],
    },
    {
        "id": "candlestick_pattern_state",
        "name": "Candlestick Pattern State",
        "description": "Encodes recent engulfing, hammer, swing, and outside-day structures.",
        "parameters": ["lookback", "pattern_family"],
        "used_by": ["candlestick_reversal_confirmation", "gap_fade_reversal"],
    },
    {
        "id": "pe_ratio",
        "name": "P/E Ratio",
        "description": "Fundamental valuation comparison for US equity peer baskets.",
        "parameters": ["peer_symbols"],
        "used_by": ["legends_inspired_technical_growth"],
    },
    {
        "id": "sector_rotation_matrix",
        "name": "Sector Rotation Matrix",
        "description": "Relative momentum quadrant model for sector and index baskets.",
        "parameters": ["benchmark", "lookback", "symbols"],
        "used_by": ["sector_rotation_relative_momentum"],
    },
]


COLLECTION_PACKS = [
    {
        "id": "opening_drive_pack",
        "name": "Opening Drive Pack",
        "description": "ORB, gap, VWAP, and volume scanners grouped for the first trading hour.",
        "scanner_ids": [
            "orb_15m_high_breakout",
            "orb_volume_gap_breakout",
            "premarket_orb_range_expansion",
            "market_open_orb_continuation",
            "vwap_reclaim",
        ],
    },
    {
        "id": "squeeze_and_expansion_pack",
        "name": "Squeeze and Expansion Pack",
        "description": "Compression, band expansion, and momentum-release scans.",
        "scanner_ids": ["bb_kc_squeeze_anchored_vwap", "upper_bollinger_band_pierce", "current_bullish_momentum"],
    },
    {
        "id": "trend_rotation_pack",
        "name": "Trend Rotation Pack",
        "description": "Moving-average, relative-strength, and sector-rotation context.",
        "scanner_ids": ["sector_rotation_matrix", "moving_average_trend_identifier", "current_bullish_momentum"],
    },
    {
        "id": "reversal_candles_pack",
        "name": "Reversal Candles Pack",
        "description": "Candlestick, swing, support/resistance, and RSI reversal candidates.",
        "scanner_ids": ["bullish_engulfing_recent_3d", "swing_detector_reversal", "rsi_divergence"],
    },
    {
        "id": "small_cap_risk_pack",
        "name": "Small Cap Risk Pack",
        "description": "Small-cap liquidity, gap, and high-percent mover watch filters.",
        "scanner_ids": ["small_cap_radar", "daily_gainers_10_pct", "high_volume_price_gappers"],
    },
    {
        "id": "legends_inspired_pack",
        "name": "Legends-Inspired Technical Growth Pack",
        "description": "Collection-style research pack distilled from publicly known investor frameworks.",
        "scanner_ids": [
            "consistent_fundamental_growth",
            "fundamental_value_technical_reversal",
            "donchian_channel_price_action",
            "support_resistance_strength",
        ],
    },
]


def scanner_workbench_catalog():
    """Return the native Edge scanner workbench catalog."""
    return {
        "schema_version": SCANNER_WORKBENCH_SCHEMA_VERSION,
        "source_policy": SCANNER_WORKBENCH_SOURCE_POLICY,
        "source_urls": deepcopy(TRENDSPIDER_PUBLIC_SOURCE_URLS),
        "counts": {
            "scanners": len(SCANNERS),
            "recommended_tickers": len(RECOMMENDED_TICKERS),
            "strategies": len(STRATEGIES),
            "indicators": len(INDICATORS),
            "collection_packs": len(COLLECTION_PACKS),
        },
        "scanners": deepcopy(SCANNERS),
        "recommended_tickers": deepcopy(RECOMMENDED_TICKERS),
        "strategies": deepcopy(STRATEGIES),
        "indicators": deepcopy(INDICATORS),
        "collection_packs": deepcopy(COLLECTION_PACKS),
    }
